pipeline:
  test:
    image: ianmaguire/trigger-warning
    commands:
      - echo "Hello world!"

  publish:
    image: https://github.com/ianmaguire/triggered
    secrets: [im_token,api_key,GITHUB_RELEASE_API_KEY]
    files: version
    when:
      event: push
      branch: master
      success: true