# dist: trusty
# sudo: required
# os: linux
language: bash
services: docker
env:
  - VERSION=1.0
  - VERSION=1.1
  - VERSION=2.0

install:
  - git clone https://github.com/ianmaguire/the-force ~/the-force

before_script:
  - env | sort
  - cd "$VERSION"
  - image="the-force:$VERSION"

script:
  - travis_retry docker build -t "$image" .
  - ~/the-force/test/run.sh "$image"

after_script:
- docker images
